modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "emotetweaks"
version = "${version}"
displayName = "Emote Tweaks"
authors = "RyanV, Wolfie"
description = '''Mod for allowing some Tweaked functionality of EmoteCraft'''
#logoFile = ""

[[dependencies.emotetweaks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emotetweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emotetweaks]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.emotetweaks]]
modId = "voicechat"
mandatory = true
versionRange = "[1.20-2.4.9,), [1.20.1-2.4.32,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.emotetweaks]]
modId = "emotecraft"
mandatory = true
versionRange = "[2.2.7-b.build,)"
ordering = "AFTER"
side = "BOTH"