modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "emotetweaks"
version = "${version}"
displayName = "Emote Tweaks"
authors = "RyanV, Wolfie"
description = '''Mod for allowing some Tweaked functionality of EmoteCraft'''
#logoFile = ""

[[dependencies.emotetweaks]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emotetweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emotetweaks]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"