name: Build & Release

on:
  push:
    paths:
      - '**.gradle'
      - '**.properties'
      - '**/src/**'
      - '.github/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Grant execute permission for gradle
        run: chmod +x gradlew

      - name: Upload to CurseForge
        run: ./gradlew publish modPublish --stacktrace
        if: |
          !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
        env:
          curse_api_key: ${{ secrets.CURSE_API_KEY }}
          modrinth_key: ${{ secrets.MODRINTH_KEY }}